# Generated by Django 4.0.3 on 2022-06-23 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0002_alter_userprofile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
